name: Test Scraper
on: workflow_dispatch

jobs: 
  scrape: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v5
    - uses: astral-sh/setup-uv
    - run: uv sync
    - run: uv run patchright install chromium
    - run: uv run gmap_scraper.py